using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RabbitMQWebAPI.Library.Models.Node
{
    public static class NodeInfoKeys
    {
        public static HashSet<string> keys = new HashSet<string>()
        {
            "cluster_links",
            "mem_userd",
            "mem_used_details",
            "fd_used",
            "fd_used_details",
            "sockets_used",
            "sockets_used_details",
            "proc_used",
            "proc_used_details",
            "disk_free",
            "disk_free_details",
            "io_read_bytes",
            "io_read_bytes_details",
            "io_read_avg_time",
            "io_read_avg_time_details",
            "io_write_count",
            "io_write_count_details",
            "io_write_bytes",
            "io_write_bytes_details",
            "io_write_avg_time",
            "io_write_avg_time_details",
            "io_sync_count",
            "io_sync_count_details",
            "io_sync_avg_time",
            "io_sync_avg_time_details",
            "io_seek_count",
            "io_seek_count_details",
            "io_seek_avg_time",
            "io_seek_avg_time_details",
            "io_reopen_count",
            "io_reopen_count_details",
            "mnesia_ram_tx_count",
            "mnesia_ram_tx_count_details",
            "mnesia_disk_tx_count",
            "mnesia_disk_tx_count_details",
            "msg_store_read_count",
            "msg_store_read_count_details",
            "msg_store_write_count",
            "msg_store_write_count_details",
            "queue_index_journal_write_count",
            "queue_index_journal_write_count_details",
            "queue_index_write_count",
            "queue_index_write_count_details",
            "queue_index_read_count",
            "queue_index_read_count_details",
            "gc_num",
            "gc_num_detail",
            "gc_bytes_reclaimed",
            "gc_bytes_reclaimed_details",
            "context_switches",
            "context_switches_details",
            "io_file_handle_open_attempt_count",
            "io_file_handle_open_attempt_count_details",
            "io_file_handle_open_attempt_avg_time",
            "io_file_handle_open_attempt_avg_time_details",
            "partitions",
            "os_pid",
            "fd_total",
            "sockets_total",
            "mem_limit",
            "mem_alarm",
            "disk_free_limit",
            "disk_free_alarm",
            "proc_total",
            "rates_mode",
            "uptime",
            "run_queue",
            "processors",
            "exchange_types",
            "auth_mechanisms",
            "applications",
            "contexts",
            "log_file",
            "sasl_log_file",
            "db_dir",
            "config_files",
            "net_ticktime",
            "enabled_plugins",
            "name",
            "type",
            "running"
        };
    }
}
